# Generated by Django 2.1.2 on 2018-11-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181113_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodAvailability',
        ),
        migrations.RemoveField(
            model_name='bloodcampdonor',
            name='bloodcamp',
        ),
        migrations.DeleteModel(
            name='BloodCamp',
        ),
        migrations.DeleteModel(
            name='BloodCampDonor',
        ),
    ]
