# Generated by Django 2.1.2 on 2018-11-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181111_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='house',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='landmark',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='locality',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
