# Generated by Django 2.1.2 on 2018-12-12 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pathlab',
            field=models.ForeignKey(default='Aditya Pathlab', on_delete=django.db.models.deletion.PROTECT, to='maps.PathlabName'),
        ),
    ]
