# Generated by Django 2.1.2 on 2018-11-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathlab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathlabuser',
            old_name='note',
            new_name='testtype',
        ),
    ]
